### ISSUE TITLE
scoring

### ISSUE THREAD

**Issue by isobretatel** [marcosan93/Stock-Performance-Predictor-2.0#1]
Should you use profit instead of F1 score?

**Comment by marcosan93** [comment]
Not necessarily.  The overall project involves classification so it is more of an issue of reducing misclassification with model.

**Comment by isobretatel** [comment]
But how do you know if better F1 Score corresponds to bigger profit?

**Comment by marcosan93** [comment]
I think you might be missing the question of the problem.  The overall project is a classification model.  F1 score evaluates how well the model classifies each quarterly report as a buy, sell, or hold not how profitable a stock will be.  You can learn more about it in the first hyperlink in the readme.
